# Generated by Django 5.2.1 on 2025-06-12 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0006_rename_teammember_membership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='unique_membership',
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('O', 'Owner'), ('M', 'Moderator'), ('D', 'Member')], default='D', max_length=1, verbose_name='Role'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='teams.Membership', through_fields=('team', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='unique_membership', violation_error_message='Membership with that user and team is already exist.'),
        ),
    ]
